### ISSUE TITLE
registry-url.js

### ISSUE THREAD

**Issue by allanhvam** [bahmutov/npm-utils#29]
The merge of pull request #27 removes src/registry-url.js but the file is still used in src/index.js

So when I try to use v1.7.0 I get the error:
```
Error: Cannot find module './registry-url'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (...\node_modules\npm-utils\src\index.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by bahmutov** [comment]
Thanks for filing the bug, will fix it soon
